### ISSUE TITLE
Do not add constants to `Cucumber` module

### ISSUE THREAD

**Issue by kratob** [makandra/cucumber_factory#18]
Cucumber_factory adds a `Cucumber::Factory` class. This kind of bothers me, I feel like a gem (that doesn't need to) should not use another gem's namespaces.

Obviously this is not a huge issue, but I would propose to
- move `Cucumber::Factory` to `CucumberFactory::Factory`
- have `Cucumber::Factory` as an alias to `CucumberFactory::Factory`, but make it print a deprecaton warning

Agree? Or not worth the effort?

**Comment by triskweline** [comment]
Sure, why not.

Since people will need to update their code anyway, how about we get rid of the weird `Cucumber::Factory.add_steps(self)` that's currently needed to install cucumber_factory. I'd much rather have people `require "cucumber_factory/steps"` in their `env.rb`.
