### ISSUE TITLE
Support or warn about values wrapped in single quotes

### ISSUE THREAD

**Issue by john-denisov** [makandra/cucumber_factory#29]
```cucumber
Given there is a user with the email 'ivan@example.com'
```
should work the same as
```cucumber
Given there is a user with the email "ivan@example.com"
```
or `cucumber_factory` gem should warn developers about possible mistake they are making by using single quotes instead of double quotes

I'm happy to code this improvement myself but I would like to first check with maintainers which approach is preferable: _support single quotes_ or _warn about single quotes_?
cc @triskweline

**Comment by triskweline** [comment]
I'm guessing that cucumber_factory silently ignored the part in single quotes, and that tripped you up.

AFAIK the current implementation accepts any step starting with `Given there is`, scans the rest of the step for patterns it recognizes and ignores the rest. I personally don't care so much for supporting single quotes, but we should do a better job of warning developers that their step doesn't parse.

My favorite implementation of this would be for cucumber_factory to blow up with an error if it *anything* after `Given there is` doesn't parse. Maybe we can grep out recognized substrings one by one and see if anything is left when we're done.

**Comment by makmic** [comment]
CucumberFactory 2.0 added support for single quotes and raises an error if any step fragments were not used after all.
