### ISSUE TITLE
Ruby 1.8: Restore or drop development support

### ISSUE THREAD

**Issue by makmic** [makandra/cucumber_factory#32]
Our [test matrix](https://github.com/makandra/cucumber_factory/blob/master/.travis.yml) includes Ruby 1.8 and Cucumber 1. In reality, it's not possible to run tests with Ruby 1, since `mysql2/client.rb` references a non-existent constant `Mysql2::Client::SECURE_CONNECTION`.

We should either fix this, or drop the Ruby 1 support.

**Comment by triskweline** [comment]
Drop support! makandra was the last user of Ruby 1, and we no longer need it.

**Comment by makmic** [comment]
Ruby 1 support was dropped in the most recent Version of CucumberFactory.
