### ISSUE TITLE
Regression in 2.1.0 when using polymorphic associations

### ISSUE THREAD

**Issue by JohannaHartmann** [makandra/cucumber_factory#37]
After upgrading to `2.1.0`, several features break with this error message:
```
Polymorphic association does not support to compute class. (ArgumentError)
```
Failing step, e.g.: `And there is a transaction with the owner "ABC-123", the amount "333" and the payment_type "E"`

- Association in the `Transaction` class: 
`belongs_to :owner, polymorphic: true, optional: true`
- Other side of association in the `Bill` class:
`  has_many :transactions, as: :owner, inverse_of: :owner`

When using version `2.0.2` it works.

**Comment by makmic** [comment]
Fixed in [2.1.1](https://github.com/makandra/cucumber_factory/tree/v2.1.1)
