### ISSUE TITLE
Cucumber_Factory 2.2.0 will break a lot of tests

### ISSUE THREAD

**Issue by FLeinzi** [makandra/cucumber_factory#41]
Hello,

I can't use a lot of steps since CF 2.2.0 anymore. Especially the time steps will break:
```
uninitialized constant TimeIs (NameError)
features/some_model/some_feature.feature:4:in `Given the time is "2019-04-11 11:00"'
```

The regular expressions `RECORD_UPDATE_PATTERN` and `UPDATE_ATTR_PATTERN` have to be more strict.

**Comment by FLeinzi** [comment]
I found out that the steps work if I require Spreewald before Cucmber_Factory.

**Comment by triskweline** [comment]
cucumber_factory should lower its step priorities so its steps are overridable by any other library and user steps.
