### ISSUE TITLE
Transient attributes raising an error for name records

### ISSUE THREAD

**Issue by denzelem** [makandra/cucumber_factory#44]
After upgrading from `2.0.0` to `2.3.1` I was not able to use named records for transient attributes anymore. The change was introduced in d42bf7ea8dd94476b881775b7950d00d08b56dad. 

## Error

Something like:

```
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT  "users".* FROM "users" WHERE (CAST(users.id AS TEXT) = 1 OR CAST(users.created_at AS TEXT) = 1 OR CAST(users.name AS TEXT) = 1 ORDER BY "users"."id" ASC LIMIT $1 (ActiveRecord::StatementInvalid)
./lib/ext/active_record/find_by_anything.rb:17:in `find_by_anything'
./spec/factories/some_factory.rb:1:in `block (3 levels) in <main>'
features/billing/some_feature:1in `And there is a page with the administrator "Bob"'
```

## Example

```
Given there is a user with the name "Bob"
  And there is a page with the administrator "Bob"
```

```
FactoryBot.define do
  factory :user do
    name { 'Some name' }
  end
  
  factory :permission do
    user
    page
  end
  
  factory :page do
    transient do
      administrator { nil } 
    end
    
    after(:create) do |page, evaluator|
      next if evaluator.administrator.blank?

      user = User.find_by_anything(administrator)
      page.permissions.create!(user: user)
    end
  end
  
end  
```

The fix for this was easy, `administrator` is already a `user`, so no need to use `find_by_anything`. 

@makmic I let you decide whether it make sense to add this to the CHANGELOG, too. I have just opened the issue, so it could be found by other devs.

**Comment by makmic** [comment]
If I understand your issue correctly, this is exactly what d42bf7e was all about. You no longer have to search for your transient associated "administrator" with `find_by_anything` but already have it loaded in `administrator`. Am I missing something? :)

**Comment by denzelem** [comment]
Fine, I think it just was me who didn't understand the changelog entry correctly. I will close this issue, no further things have to be done.

**Comment by makmic** [comment]
Ok. Thank you for writing down your issue!
I'll further elaborate the altered behavior in the changelog if this issue receives similar feedback from more users.
