### ISSUE TITLE
Transforms are not working for associations

### ISSUE THREAD

**Issue by codener** [makandra/cucumber_factory#9]
CucumberFactory does not apply `Transform`s to associations: https://github.com/makandra/cucumber_factory/blob/6c42665224d5d2550f5543652064b2fdddb7d758/lib/cucumber/factory.rb#L88

It would be nice to have Transforms available for associations.

**Comment by henning-koch** [comment]
Can't we even not apply transforms?

I always thought that transforms are automatically applied to each step, before a step definitions (and hence, CucumberFactory) are invoked.

**Comment by kratob** [comment]
Transforms are invoked on each captured argument. Cucumber factory captures everything after `Given there is` so the transform is applied to `a movie with the title "Interstellar"` and not to `Interstellar`.

**Comment by henning-koch** [comment]
Bummer.

**Comment by kratob** [comment]
For attribute values, we already do this manually: https://github.com/makandra/cucumber_factory/blob/master/lib/cucumber/factory.rb#L95

**Comment by kratob** [comment]
This was fixed in #17.

**Comment by codener** [comment]
Thanks!
